### ISSUE TITLE
Can't reach gameobject in Initialize() method

### ISSUE THREAD

**Issue by ahmetyazir22** [jedybg/yaSingleton#2]
```
protected override void Initialize()
{
    base.Initialize();
    gameContainer = GameObject.Find("Game"); //Pretty sure there is a "Game" gameobject in the hierarchy.
    Debug.Log(gameContainer.name); // Gives null error!
}
```
![image](https://user-images.githubusercontent.com/33584207/78576044-d1b2a600-7834-11ea-8e25-fbbef9efbaf1.png)

**Comment by ahmetyazir22** [comment]
I think the issue is related to the order AllSingletons are initialized.
![image](https://user-images.githubusercontent.com/33584207/78593147-d4ba9000-784e-11ea-8d72-8ae7ba82512d.png)
If I change the name of EventManager so that it is added to the AllSingletons array first, then the problem does not occur.
![image](https://user-images.githubusercontent.com/33584207/78593315-1ba88580-784f-11ea-8798-08d0f3ad97d3.png)
However, this is not a permanent solution because all my singletons should be able to reach each other at the beginning without taking their initialization order into account. LazySingleton helps a little though.

**Comment by heyJordanParker** [comment]
@ahmetyazir22 

Hey ho,

The singleton initialization occurs before any scene has loaded. This is by design.

You can use the Start() method to interact with the scene and there will be no errors.

Cheers!
