### ISSUE TITLE
Make it a package please!

### ISSUE THREAD

**Issue by landosilva** [jedybg/yaSingleton#7]
I love this asset but using it as a submodule makes no sense with the rest of the Unity's project architecture. Please either make it a package or upload in the asset store! 🙏

**Comment by heyJordanParker** [comment]
Hey ho,

It's on the asset store: https://assetstore.unity.com/packages/tools/integration/yasingleton-116633 

(might be a bit of an older version, but I don't currently have a setup environment to fix that)

PS: I'd appreciate you adding the changes necessary to make it a package; I'll gladly approve them!
